"""Generate shared raw register definitions from the LTC4162 readout dictionary."""
import json
from pathlib import Path
import sys

D = json.loads(Path(__file__).with_name('ltc4162.json').read_text())


def generate(path):
    lines=['/* Generated by ground/ember/generate_ltc4162.py; do not edit. */',
           '#pragma once', '#include <stdint.h>',
           '#define LTC4162_READOUT_REGISTERS(X) \\']
    for i,r in enumerate(D['registers']):
        lines.append('    X(%s, 0x%02Xu)%s' % (r['name'],r['address'],' \\' if i+1<len(D['registers']) else ''))
    lines += ['#define LTC4162_REG_DEFINE(name, address) enum { LTC4162_REG_##name = address };',
              'LTC4162_READOUT_REGISTERS(LTC4162_REG_DEFINE)', '#undef LTC4162_REG_DEFINE',
              'typedef struct {', '#define LTC4162_FIELD(name, address) uint16_t name;',
              '    LTC4162_READOUT_REGISTERS(LTC4162_FIELD)', '#undef LTC4162_FIELD',
              '} ltc4162_raw_t;']
    Path(path).write_text('\n'.join(lines)+'\n')


if __name__=='__main__':
    generate(sys.argv[1])
