/* Generated by ground/ember/generate_ltc4162.py; do not edit. */
#pragma once
#include <stdint.h>
#define LTC4162_READOUT_REGISTERS(X) \
    X(config_bits, 0x14u) \
    X(charger_config_bits, 0x29u) \
    X(charger_state, 0x34u) \
    X(charge_status, 0x35u) \
    X(limit_alerts, 0x36u) \
    X(charger_state_alerts, 0x37u) \
    X(charge_status_alerts, 0x38u) \
    X(system_status, 0x39u) \
    X(vbat, 0x3Au) \
    X(vin, 0x3Bu) \
    X(vout, 0x3Cu) \
    X(ibat, 0x3Du) \
    X(iin, 0x3Eu) \
    X(die_temp, 0x3Fu) \
    X(thermistor_voltage, 0x40u) \
    X(bsr, 0x41u) \
    X(jeita_region, 0x42u) \
    X(chem_cells, 0x43u) \
    X(telemetry_status, 0x4Au)
#define LTC4162_REG_DEFINE(name, address) enum { LTC4162_REG_##name = address };
LTC4162_READOUT_REGISTERS(LTC4162_REG_DEFINE)
#undef LTC4162_REG_DEFINE
typedef struct {
#define LTC4162_FIELD(name, address) uint16_t name;
    LTC4162_READOUT_REGISTERS(LTC4162_FIELD)
#undef LTC4162_FIELD
} ltc4162_raw_t;
